accounts:
  test_bot:                                     # 录播账号 ID 用来在房间里对应
    name: 熊卡录播bot                             # 录播账号的名字，可以用于模版
    # sessdata 和 bili_jct 获取见：https://bili.moyu.moe/#/get-credential
    sessdata: "sessdata"                         # SESSDATA cookie
    bili_jct: "bili_jct"                         # bili_jct cookie
    line: "kodo"                                 # 选择上传线路，见 https://biliup.github.io/upload-systems-analysis.html
rooms:
  - id: 128308                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: test_bot                           # 上传所应使用的账号 ID
    tags: "录播,直播录屏,熊卡,碳酸熊卡"              # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/261"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
      录播源文件 https://tsxk.jya.ng/$flv_path
